### ISSUE TITLE
Add an app to the website

### ISSUE THREAD

**Issue by mp2023** [ethereumclassic/ethereumclassic.github.io#824]
Would like to add an app to the page: https://ethereumclassic.org/services/apps.

**Comment by IstoraMandiri** [comment]
Please could you provide the details?

**Comment by mp2023** [comment]
Hello,

I would like to add our app, Matrixport <https://www.matrixport.com/>to
this page: https://ethereumclassic.org/services/apps .

Can you let me know what information I can provide to you to be included on
this page?

Thanks,


<https://www.matrixport.com/>
<https://www.instagram.com/matrixport_/>
<https://www.youtube.com/channel/UCEn2AjmjhFAziCSG0IVS8iw/videos>
<https://twitter.com/realMatrixport> <https://t.me/matrixport>
<https://www.facebook.com/matrixport>

*Karen Wong*
Senior Manager, SEO & ASO

*Get More FromYour Crypto*


***@***.***

**Comment by w1g0** [comment]
@IstoraMandiri what more details are needed from @mp2023 to proceed with this issue?

**Comment by IstoraMandiri** [comment]
Sorry, I should be more specific in future for these kinds of requests and perhaps #846 

For now, we need the details that can fill out something like this:

What is missing right now is type, description, etc.

```
- title: Multichain
  date: 2022-05-23
  image: ./images/multichain.png
  author: Multichain
  authorLink: https://multichain.org
  verifiedContract: https://blockscout.com/etc/mainnet/address/0x5D9ab5522c64E1F6ef5e3627ECCc093f56167818/contracts
  openSource: https://blockscout.com/etc/mainnet/address/0x5D9ab5522c64E1F6ef5e3627ECCc093f56167818/contracts
  audit: https://github.com/anyswap/Anyswap-Audit
  teamSite: https://ethereumclassicdao.org
  description: Multichain is the ultimate Router for web3. It is an infrastructure developed for arbitrary cross-chain interactions.
  type: interoperability
  links:
    - name: Launch Router
      link: https://app.multichain.org/#/router
      icon: link
    - name: Website
      link: https://multichain.org
      icon: home
    - name: Documentation
      link: https://docs.multichain.org
      icon: book
    - name: Github
      link: https://github.com/anyswap
      icon: github
    - name: Twitter
      link: https://twitter.com/MultichainOrg
      icon: twitter
    - name: Telegram
      link: https://t.me/anyswap
      icon: telegram
    - name: Medium
      link: https://medium.com/multichainorg
      icon: medium
```
